/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Property, BrokerProfile, AgentProfile, SubscriptionPlan, Inquiry, Appointment, ChatMessage } from './types';

export const INITIAL_BROKERS: BrokerProfile[] = [
  {
    id: 'broker-1',
    companyName: 'Habesha Elite Realty',
    logo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=150&q=80',
    address: 'Bole, Near Edna Mall, Addis Ababa',
    phone: '+251 911 123 456',
    email: 'info@habeshaelite.com',
    website: 'https://www.habeshaeliterealty.com',
    licenseNumber: 'L-AA-2026-9081',
    rating: 4.8,
    reviewsCount: 42,
    status: 'approved',
  },
  {
    id: 'broker-2',
    companyName: 'AfroLand Premium Brokers',
    logo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=150&q=80',
    address: 'Kazanchis, UNECA Road, Addis Ababa',
    phone: '+251 922 987 654',
    email: 'contact@afroland.et',
    website: 'https://www.afroland.et',
    licenseNumber: 'L-AA-2026-0922',
    rating: 4.5,
    reviewsCount: 19,
    status: 'approved',
  },
  {
    id: 'broker-3',
    companyName: 'Abyssinia Investment Group',
    logo: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=150&q=80',
    address: 'CMC Road, Near Gibson School, Addis Ababa',
    phone: '+251 910 555 444',
    email: 'invest@abyssinia.et',
    website: 'https://www.abyssiniainvest.et',
    licenseNumber: 'L-AA-2026-4412',
    rating: 4.9,
    reviewsCount: 31,
    status: 'approved',
  },
];

export const INITIAL_AGENTS: AgentProfile[] = [
  {
    id: 'agent-1',
    name: 'Yonas Kebede',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80',
    phone: '+251 911 888 777',
    email: 'yonas@habeshaelite.com',
    brokerId: 'broker-1',
    status: 'approved',
  },
  {
    id: 'agent-2',
    name: 'Selam Hailu',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80',
    phone: '+251 911 999 666',
    email: 'selam@habeshaelite.com',
    brokerId: 'broker-1',
    status: 'approved',
  },
  {
    id: 'agent-3',
    name: 'Henok Tadesse',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80',
    phone: '+251 922 111 222',
    email: 'henok@afroland.et',
    brokerId: 'broker-2',
    status: 'approved',
  },
];

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    title: 'Luxury 5-Bedroom Villa with Swimming Pool',
    description: 'A magnificent custom-built modern villa situated in the highly secure, prestigious diplomatic area of Bole, Addis Ababa. Features multiple large living rooms, an ultra-modern kitchen with high-end appliances, a swimming pool, a fully manicured garden, separate maids quarters, ample garage spaces for up to 5 vehicles, full backup generator, high-capacity water reservoir, and state-of-the-art security installations.',
    price: 350000,
    currency: 'USD',
    type: 'Villa',
    category: 'Residential',
    purpose: 'Sale',
    bedrooms: 5,
    bathrooms: 6,
    garage: true,
    kitchen: true,
    livingRooms: 2,
    balcony: true,
    area: 650,
    floor: 2,
    buildingAge: 2,
    latitude: 9.0115,
    longitude: 38.7954,
    address: 'Bole, Near Edna Mall',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    subCity: 'Bole',
    woreda: 'Woreda 03',
    nearbySchools: 'Bole High School, International Community School (ICS)',
    nearbyHospitals: 'Hayat Hospital, Myungsung Christian Medical Centre (MCM)',
    nearbyBanks: 'Commercial Bank of Ethiopia (CBE), Awash Bank',
    nearbyRoads: 'Bole Road, Ring Road',
    water: true,
    electricity: true,
    internet: true,
    parking: true,
    security: true,
    furnished: true,
    swimmingPool: true,
    garden: true,
    videoTour: 'https://www.w3schools.com/html/mov_bbb.mp4',
    virtualTour360: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&q=80',
    ownershipStatus: 'Clean Title',
    propertyCondition: 'Excellent',
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      'https://images.unsplash.com/photo-1615529182904-14819c35db37?w=800&q=80'
    ],
    status: 'active',
    brokerId: 'broker-1',
    agentId: 'agent-1',
    isPremium: true,
    isFeatured: true,
    createdAt: '2026-06-20T10:00:00Z',
  },
  {
    id: 'prop-2',
    title: 'Elegant 2-Bedroom Condo in Kazanchis',
    description: 'This chic, premium apartment is perfectly situated in Kazanchis, the business hub of Addis Ababa, with spectacular views of the UNECA complex and Sheraton Addis. Designed with modern European finishes, beautiful hardwood flooring, open kitchen style with integrated appliances, smart security system, and double glazed noise-reduction windows. Highly suitable for international consultants and expats.',
    price: 180000,
    currency: 'ETB',
    type: 'Apartment',
    category: 'Residential',
    purpose: 'Sale',
    bedrooms: 2,
    bathrooms: 2,
    garage: true,
    kitchen: true,
    livingRooms: 1,
    balcony: true,
    area: 120,
    floor: 8,
    buildingAge: 4,
    latitude: 9.0210,
    longitude: 38.7690,
    address: 'Kazanchis, Near UNECA Headquarters',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    subCity: 'Kirkos',
    woreda: 'Woreda 04',
    nearbySchools: 'Saint Joseph School',
    nearbyHospitals: 'Zewditu Hospital, Landmark Hospital',
    nearbyBanks: 'Dashen Bank, Abyssinia Bank, CBE',
    nearbyRoads: 'Yoly Road, Menelik II Avenue',
    water: true,
    electricity: true,
    internet: true,
    parking: true,
    security: true,
    furnished: false,
    swimmingPool: false,
    garden: false,
    virtualTour360: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=1200&q=80',
    ownershipStatus: 'Clean Title',
    propertyCondition: 'New',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80'
    ],
    status: 'active',
    brokerId: 'broker-2',
    agentId: 'agent-3',
    isPremium: false,
    isFeatured: true,
    createdAt: '2026-06-25T14:30:00Z',
  },
  {
    id: 'prop-3',
    title: 'Spacious Commercial Building in Mercato',
    description: 'A multi-story commercial shop complex located in the heart of Mercato, Africa\'s largest open-air market. Features active foot traffic with immense business exposure, 12 separate retail spaces, full safety exits, storage warehouses, loading docks, separate toilet rooms on each level, and dual street access points. Perfect investment for wholesale merchants and retail chains looking for maximum ROI.',
    price: 150000000,
    currency: 'ETB',
    type: 'Building',
    category: 'Commercial',
    purpose: 'Sale',
    bedrooms: 0,
    bathrooms: 8,
    garage: false,
    kitchen: false,
    livingRooms: 0,
    balcony: false,
    area: 450,
    floor: 4,
    buildingAge: 7,
    latitude: 9.0305,
    longitude: 38.7412,
    address: 'Mercato, Near Raguel Church',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    subCity: 'Addis Ketema',
    woreda: 'Woreda 01',
    nearbySchools: 'Bethel Academy',
    nearbyHospitals: 'Tiku Anbessa Hospital',
    nearbyBanks: 'Awash Bank, CBE, Oromia Bank',
    nearbyRoads: 'Fitawrari Habte Giorgis Street',
    water: true,
    electricity: true,
    internet: false,
    parking: false,
    security: true,
    furnished: false,
    swimmingPool: false,
    garden: false,
    ownershipStatus: 'Clean Title',
    propertyCondition: 'Good',
    images: [
      'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800&q=80',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80'
    ],
    status: 'active',
    brokerId: 'broker-2',
    agentId: 'agent-3',
    isPremium: true,
    isFeatured: false,
    createdAt: '2026-06-15T09:15:00Z',
  },
  {
    id: 'prop-4',
    title: 'High-Capacity Warehouse in Akaki-Kality',
    description: 'An expansive industrial warehouse facility measuring 2,500 square meters located in the industrial gateway of Akaki-Kality. Features high-clearance ceilings suitable for heavy machinery and high-density racking, reinforced concrete floors, dedicated 3-phase high-voltage power transformer, secure container truck loading terminals, and comprehensive fire suppression equipment.',
    price: 250000, // ETB/month
    currency: 'ETB',
    type: 'Warehouse',
    category: 'Commercial',
    purpose: 'Rent',
    bedrooms: 0,
    bathrooms: 4,
    garage: true,
    kitchen: false,
    livingRooms: 0,
    balcony: false,
    area: 2500,
    floor: 1,
    buildingAge: 5,
    latitude: 8.8950,
    longitude: 38.7880,
    address: 'Kality Industrial Zone',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    subCity: 'Akaki-Kality',
    woreda: 'Woreda 08',
    nearbySchools: 'Kality Technical College',
    nearbyHospitals: 'Kality Health Center',
    nearbyBanks: 'CBE, Wegagen Bank',
    nearbyRoads: 'Addis-Adama Expressway',
    water: true,
    electricity: true,
    internet: true,
    parking: true,
    security: true,
    furnished: false,
    swimmingPool: false,
    garden: false,
    ownershipStatus: 'Clean Title',
    propertyCondition: 'Excellent',
    images: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80'
    ],
    status: 'active',
    brokerId: 'broker-1',
    agentId: 'agent-2',
    isPremium: true,
    isFeatured: true,
    createdAt: '2026-06-28T11:00:00Z',
  },
  {
    id: 'prop-5',
    title: 'Prime Residential Land in CMC',
    description: 'A perfect rectangular plot of residential land measuring 500 square meters, situated in a peaceful gated-like community in CMC. Directly accessible via an asphalt road, with pre-approved building plans for a luxurious 3-story G+2 residential house. All utility networks (water, fiber internet, electricity) are readily available on site.',
    price: 22000000,
    currency: 'ETB',
    type: 'Residential Land',
    category: 'Land',
    purpose: 'Sale',
    bedrooms: 0,
    bathrooms: 0,
    garage: false,
    kitchen: false,
    livingRooms: 0,
    balcony: false,
    area: 500,
    floor: 0,
    buildingAge: 0,
    latitude: 9.0180,
    longitude: 38.8250,
    address: 'CMC Gated Area, Near Ayat Compound',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    subCity: 'Yeka',
    woreda: 'Woreda 11',
    nearbySchools: 'Gibson School, Fountain Academy',
    nearbyHospitals: 'Yeka General Hospital',
    nearbyBanks: 'Awash Bank, Abyssinia Bank',
    nearbyRoads: 'CMC Main Road',
    water: true,
    electricity: true,
    internet: true,
    parking: false,
    security: true,
    furnished: false,
    swimmingPool: false,
    garden: false,
    ownershipStatus: 'Clean Title',
    propertyCondition: 'New',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80'
    ],
    status: 'active',
    brokerId: 'broker-3',
    agentId: 'agent-1',
    isPremium: false,
    isFeatured: false,
    createdAt: '2026-06-18T16:00:00Z',
  },
  {
    id: 'prop-6',
    title: 'Exquisite Lakeside Resort in Bishoftu',
    description: 'An operating premium resort located on the breathtaking crater lakes of Bishoftu (Debre Zeyit). Set on 8,000 square meters of beautifully landscaped grounds, featuring 24 luxury guest villas, a high-capacity restaurant & bar with scenic lake viewing decks, a temperature-controlled swimming pool, full spa & wellness center, and extensive conference facilities. Fully operational with premium bookings.',
    price: 4500000,
    currency: 'USD',
    type: 'Resort',
    category: 'Special',
    purpose: 'Sale',
    bedrooms: 24,
    bathrooms: 28,
    garage: true,
    kitchen: true,
    livingRooms: 4,
    balcony: true,
    area: 8000,
    floor: 1,
    buildingAge: 4,
    latitude: 8.7520,
    longitude: 38.9880,
    address: 'Lake Babogaya Road, Bishoftu',
    region: 'Oromia',
    city: 'Bishoftu',
    subCity: 'Bishoftu',
    woreda: 'Woreda 02',
    nearbySchools: 'Bishoftu Academy',
    nearbyHospitals: 'Bishoftu General Hospital',
    nearbyBanks: 'CBE, Cooperative Bank of Oromia',
    nearbyRoads: 'Expressway Connector Road',
    water: true,
    electricity: true,
    internet: true,
    parking: true,
    security: true,
    furnished: true,
    swimmingPool: true,
    garden: true,
    videoTour: 'https://www.w3schools.com/html/mov_bbb.mp4',
    ownershipStatus: 'Leasehold',
    propertyCondition: 'Excellent',
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
      'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80'
    ],
    status: 'active',
    brokerId: 'broker-3',
    isPremium: true,
    isFeatured: true,
    createdAt: '2026-06-01T08:00:00Z',
  }
];

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'Free',
    name: 'Free Starter',
    price: 0,
    durationMonths: 1,
    features: ['Upload up to 3 properties', 'Standard search listings', 'Basic email inquiry receipts', 'No premium priority display'],
  },
  {
    id: 'Silver',
    name: 'Silver Growth',
    price: 3500,
    durationMonths: 1,
    features: ['Upload up to 15 properties', 'Silver badge on profile', 'Direct inquiries via Live Chat', 'Featured tag for 2 listings', 'Access to Broker Admin panel'],
  },
  {
    id: 'Gold',
    name: 'Gold Professional',
    price: 7500,
    durationMonths: 1,
    features: ['Upload up to 50 properties', 'Gold verified badge', 'Push notifications alerts', 'SMS listing alerts to matches', 'Telegram Bot property listing upload', 'Featured tag for 10 listings', 'Custom SEO tags'],
  },
  {
    id: 'Premium',
    name: 'Premium Enterprise',
    price: 15000,
    durationMonths: 1,
    features: ['Unlimited properties', 'Premium partner badge', 'Instant lead synchronization', 'Full custom analytics dashboard', 'Premium properties displayed first', 'Dedicated Account Manager', 'Custom Android App ad banner space'],
  },
];

export const INITIAL_INQUIRIES: Inquiry[] = [
  {
    id: 'inq-1',
    propertyId: 'prop-1',
    propertyTitle: 'Luxury 5-Bedroom Villa with Swimming Pool',
    customerName: 'Alemayehu Tessema',
    customerEmail: 'alemayehu@gmail.com',
    customerPhone: '+251 911 445 566',
    message: 'I am highly interested in purchasing this villa. Can we schedule a physical tour for next Wednesday morning? Please let me know if that works.',
    method: 'Telegram',
    status: 'new',
    brokerId: 'broker-1',
    agentId: 'agent-1',
    createdAt: '2026-07-01T15:20:00Z'
  },
  {
    id: 'inq-2',
    propertyId: 'prop-2',
    propertyTitle: 'Elegant 2-Bedroom Condo in Kazanchis',
    customerName: 'Sarah Jenkins',
    customerEmail: 'sjenkins@uneca.org',
    customerPhone: '+251 909 334 455',
    message: 'Hello, I am an expat arriving at ECA soon. Does the apartment include cleaning services or full backup utilities? Thank you.',
    method: 'Live Chat',
    status: 'new',
    brokerId: 'broker-2',
    agentId: 'agent-3',
    createdAt: '2026-07-01T18:45:00Z'
  }
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-1',
    propertyId: 'prop-1',
    propertyTitle: 'Luxury 5-Bedroom Villa with Swimming Pool',
    customerId: 'cust-101',
    customerName: 'Alemayehu Tessema',
    customerPhone: '+251 911 445 566',
    date: '2026-07-08',
    time: '10:00 AM',
    status: 'pending',
    brokerId: 'broker-1',
    agentId: 'agent-1',
    createdAt: '2026-07-01T15:21:00Z'
  }
];

export const INITIAL_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    channelId: 'chat_broker-1_buyer',
    senderId: 'buyer',
    senderName: 'Michael Demissie',
    text: 'Hello! I saw your luxury Bole Villa on the Property Hub.',
    timestamp: '2026-07-01T10:05:00Z'
  },
  {
    id: 'msg-2',
    channelId: 'chat_broker-1_buyer',
    senderId: 'agent-1',
    senderName: 'Yonas Kebede',
    text: 'Hello Michael! Welcome to Habesha Elite Realty. Yes, the Bole Villa is currently active and open for viewings. It has a beautiful swimming pool and 5 bedrooms. Would you like to check it out?',
    timestamp: '2026-07-01T10:07:00Z'
  },
  {
    id: 'msg-3',
    channelId: 'chat_broker-1_buyer',
    senderId: 'buyer',
    senderName: 'Michael Demissie',
    text: 'Excellent, yes! Is the price open for negotiation, and does it have a clean title deed?',
    timestamp: '2026-07-01T10:10:00Z'
  },
  {
    id: 'msg-4',
    channelId: 'chat_broker-1_buyer',
    senderId: 'agent-1',
    senderName: 'Yonas Kebede',
    text: 'Absolutely, we have the clean ownership documents on file with no bank collateral. The owner is open to reasonable USD offers. Here is our head office location if you want to drop by!',
    timestamp: '2026-07-01T10:12:00Z',
    location: { lat: 9.0112, lng: 38.7950 }
  }
];
